- name: Setup VMs in group2
  hosts: vm_group2
  become: yes
  strategy: free

  tasks:
    - name: Add server custom DNS entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['vm_ip'] }} {{ hostvars[item]['hostname'] }}"
        state: present
      with_items: "{{ groups['baremetal'] }}"

    - name: Add VM group custom DNS entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['vm_ip'] }} {{ hostvars[item]['hostname'] }}"
        state: present
      with_items: "{{ groups['vm_group2'] }}"

    - name: Install require packages
      apt:
        name:
          - linux-image-generic-hwe-22.04
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: yes

    - name: Remove snap package manager
      apt:
        name: snapd
        state: absent

    - name: Upgrade packages
      apt:
        upgrade: 'yes'
        update_cache: yes
        autoremove: yes
        autoclean: yes

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker-archive-keyring
        mode: '0644'

    - name: Import Docker GPG key
      command: gpg --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg --dearmor /tmp/docker-archive-keyring

    - name: Add Docker APT repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        create: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce=5:20.10.23~3-0~ubuntu-jammy
          - docker-ce-cli=5:20.10.23~3-0~ubuntu-jammy
          - containerd.io=1.6.15-1
        update_cache: yes

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure /etc/docker directory exists
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure insecure registry in daemon.json
      template:
        src: config/docker-daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'

    - name: Reboot to run new kernel
      reboot: